export default {
  "login": "rudragouda-patil5913",
"id": 88940283,
"node_id": "MDQ6VXNlcjg4OTQwMjgz",
"avatar_url": "https://avatars.githubusercontent.com/u/88940283?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/rudragouda-patil5913",
"html_url": "https://github.com/rudragouda-patil5913",
"followers_url": "https://api.github.com/users/rudragouda-patil5913/followers",
"following_url": "https://api.github.com/users/rudragouda-patil5913/following{/other_user}",
"gists_url": "https://api.github.com/users/rudragouda-patil5913/gists{/gist_id}",
"starred_url": "https://api.github.com/users/rudragouda-patil5913/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/rudragouda-patil5913/subscriptions",
"organizations_url": "https://api.github.com/users/rudragouda-patil5913/orgs",
"repos_url": "https://api.github.com/users/rudragouda-patil5913/repos",
"events_url": "https://api.github.com/users/rudragouda-patil5913/events{/privacy}",
"received_events_url": "https://api.github.com/users/rudragouda-patil5913/received_events",
"type": "User",
"site_admin": false,
"name": "Rudragouda Patil",
"company": "Cognizant Technology Solutions",
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "Programmer Analyst in Cognizant.",
"twitter_username": null,
"public_repos": 11,
"public_gists": 0,
"followers": 0,
"following": 1,
"created_at": "2021-08-14T15:57:05Z",
"updated_at": "2022-02-05T11:07:09Z",
};